/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ltmui.frames;

import components.GroupCreator;
import components.RoomCreator;

/**
 *
 * @author hirosume
 */
public class RoomCreatorPanel extends javax.swing.JPanel {

	/**
	 * Creates new form RoomCreatorPanel
	 */
	public RoomCreatorPanel() {
		initComponents();
		init();
	}
	private void init() {
		this.RoomPanel.add(new RoomCreator());
		this.GroupPanel.add(new GroupCreator());
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        RoomPanel = new javax.swing.JPanel();
        GroupPanel = new javax.swing.JPanel();

        jLabel1.setText("Tạo phòng mới ");

        jTabbedPane1.setBackground(new java.awt.Color(181, 181, 181));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        RoomPanel.setLayout(new javax.swing.BoxLayout(RoomPanel, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane1.addTab("Phòng thông thường ", RoomPanel);

        GroupPanel.setLayout(new javax.swing.BoxLayout(GroupPanel, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane1.addTab("Nhóm ", GroupPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GroupPanel;
    private javax.swing.JPanel RoomPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
