/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import packets.GroupCreatePacket;
import utils.GroupCreatorListener;
import vendor.Vendor;

/**
 *
 * @author hirosume
 */
public class GroupCreator extends javax.swing.JPanel {

	/**
	 * Creates new form GroupCreator
	 */
	public GroupCreator() {
		initComponents();
		new GroupCreatorListener();
	}

	private void createNewGroup() {
		Vendor.getClient().send(new GroupCreatePacket(this.groupNameText.getText()));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        groupNameText = new javax.swing.JTextField();
        createGroupButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Tên phòng");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 54, -1, -1));

        groupNameText.setText("Tên nhóm");
        add(groupNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 90, 130, -1));

        createGroupButton.setText("Tạo nhóm");
        createGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupButtonActionPerformed(evt);
            }
        });
        add(createGroupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 136, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupButtonActionPerformed
		// TODO add your handling code here:
		createNewGroup();
    }//GEN-LAST:event_createGroupButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createGroupButton;
    private javax.swing.JTextField groupNameText;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
