/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import packets.RoomCreatePacket;
import packets.UserFindPacket;
import utils.RoomCreatorListener;
import vendor.Vendor;

/**
 *
 * @author hirosume
 */
public class RoomCreator extends javax.swing.JPanel {

	DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();

	/**
	 * Creates new form RoomCreator
	 */
	public RoomCreator() {
		initComponents();
		init();
	}

	private void init() {
		new RoomCreatorListener(this);
		Vendor.getClient().send(new UserFindPacket(""));
	}

	public void onListUsername(ArrayList<String> usernames) {
		this.comboModel.removeAllElements();
		String username = Vendor.getUsername();
		usernames.forEach(i -> {
			if (!i.equals(username)) {
				this.comboModel.addElement(i);
			}
		});
		this.friendChooser.repaint();
	}

	private void computeRoomName(String name) {
		String username = Vendor.getUsername().toUpperCase();
		String roomName = username.charAt(0) + "";
		roomName += ("" + name.toUpperCase().charAt(0));
		this.roomNameText.setText(roomName);
	}

	private void createRoom() {
		Vendor.getClient().send(new RoomCreatePacket((String) this.comboModel.getSelectedItem(), this.roomNameText.getText()));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        roomNameText = new javax.swing.JTextField();
        friendChooser = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel3.setText("Tên phòng");

        roomNameText.setText("Tên phòng");

        friendChooser.setModel(comboModel);
        friendChooser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                friendChooserItemStateChanged(evt);
            }
        });

        jLabel2.setText("Chọn bạn bè");

        jButton1.setText("Tạo phòng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(roomNameText))
                                .addComponent(friendChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(207, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(roomNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(friendChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void friendChooserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_friendChooserItemStateChanged
		// TODO add your handling code here:
		if (evt.getStateChange() == ItemEvent.SELECTED) {
			computeRoomName((String) evt.getItem());
		}
    }//GEN-LAST:event_friendChooserItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		this.createRoom();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> friendChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField roomNameText;
    // End of variables declaration//GEN-END:variables
}
