/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.util.Date;
import packets.RoomPacket;

/**
 *
 * @author hirosume
 */
public class Room extends javax.swing.JPanel {
	String name ="NaN";
	Date date = new Date();
	int id = -1;
	RoomList.OnChange onchange;
	
	public void register(RoomList.OnChange on) {
		this.onchange = on;
	}
	/**
	 * Creates new form Room
	 */
	public Room() {
		initComponents();
	}
	public Room(String name, Date date, int id) {
		this.name = name;
		this.date = date;
		this.id = id;
		initComponents();
	}
	
	public static Room fromPacket(RoomPacket p) {
		return new Room(p.getCreator(), p.getUpdate_time(), p.getId());
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomName = new javax.swing.JLabel();
        lastMesssage = new javax.swing.JLabel();
        roomTime = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        roomName.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        roomName.setText(name);

        lastMesssage.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lastMesssage.setText("jLabel2");

        roomTime.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        roomTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roomTime.setText(date.toString());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastMesssage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roomName)
                        .addGap(18, 18, 18)
                        .addComponent(roomTime)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomName)
                    .addComponent(roomTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastMesssage)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
		if(this.onchange != null) {
			onchange.execute(id);
		}
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lastMesssage;
    private javax.swing.JLabel roomName;
    private javax.swing.JLabel roomTime;
    // End of variables declaration//GEN-END:variables
}
